package esports.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import esports.entity.Participant;
import esports.repository.ParticipantRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/participants")
public class ParticipantController {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private ParticipantRepository participantRepository;

	@GetMapping(path = "/all")
	public @ResponseBody Iterable<Participant> getAllEquipes() {
		// This returns a JSON or XML with the users
		return participantRepository.findAll();
	}
}
