package esports.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import esports.entity.PhaseQualification;
import esports.repository.PhaseQualificationRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/phasequalifications")
public class PhaseQualificationController {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private PhaseQualificationRepository phasequalificationRepository;

	@GetMapping(path = "/all")
	public @ResponseBody Iterable<PhaseQualification> getAllPhasequalifications() {
		// This returns a JSON or XML with the users
		return phasequalificationRepository.findAll();
	}
}
