package esports.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import esports.entity.Score;
import esports.repository.ScoreRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/scores")
public class ScoreController {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private ScoreRepository scoreRepository;

	@GetMapping(path = "/all")
	public @ResponseBody Iterable<Score> getAllScores() {
		// This returns a JSON or XML with the users
		return scoreRepository.findAll();
	}
}
